"""Generate SPSA inputs from the search-parameter X-macro.

The C++ table owns option names, defaults, and bounds.  This generator derives
the registered integer perturbation as max(2, round((max - min) / 16)) and
writes both weather-factory JSON and Colosseum TOML.  Generated files are
checked into the tree so experiment registrations can name an exact surface;
edit the X-macro and regenerate rather than editing them.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys

GAMMA = 0.102
DEFAULT_ITERATIONS = 2_000
ROOT = pathlib.Path(__file__).resolve().parents[1]
HEADER = ROOT / "src" / "search_params.h"
CONFIG = ROOT / "tools" / "spsa_configs" / "config_search.json"
COLOSSEUM = ROOT / "tools" / "spsa_configs" / "colosseum"
TUNE = COLOSSEUM / "search.tune.toml"
RUN = COLOSSEUM / "search.run.toml"
PARAM_RE = re.compile(
    r"^\s*X\(\s*[a-z][a-z0-9_]*\s*,\s*([A-Za-z][A-Za-z0-9]*)\s*,"
    r"\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*\)"
)
# The B2_CORE arm's kernel table. The registered surface is the default
# arm's (the root and legacy kernel tables), so its lines are skipped; the
# core arm's surface is generated when its tune is registered.
CORE_TABLE = "#define BASILISK_CORE_KERNEL_PARAMS(X)"


def default_arm_lines(text: str) -> list[str]:
    lines = []
    in_core = False
    for line in text.splitlines():
        if line.startswith(CORE_TABLE):
            in_core = True
        if not in_core:
            lines.append(line)
        elif not line.rstrip().endswith("\\"):
            in_core = False
    return lines


def parse_parameters(text: str) -> list[tuple[str, int, int, int]]:
    parameters = []
    seen = set()
    for line in default_arm_lines(text):
        match = PARAM_RE.match(line)
        if not match:
            continue
        name, default, minimum, maximum = match.groups()
        values = tuple(map(int, (default, minimum, maximum)))
        if name in seen:
            raise ValueError(f"duplicate UCI option {name}")
        if not values[1] <= values[0] <= values[2]:
            raise ValueError(f"{name}: default {values[0]} outside [{values[1]}, {values[2]}]")
        if values[1] == values[2]:
            raise ValueError(f"{name}: empty range")
        seen.add(name)
        parameters.append((name, *values))
    if not parameters:
        raise ValueError("no BASILISK_SEARCH_PARAMS entries found")
    return parameters


def perturbation(minimum: int, maximum: int) -> int:
    # Positive integer half-up rounding; unlike Python round(), ties do not
    # depend on parity.
    return max(2, (maximum - minimum + 8) // 16)


def render(parameters: list[tuple[str, int, int, int]], iterations: int) -> dict[pathlib.Path, str]:
    surface = {
        name: {
            "value": default,
            "min_value": minimum,
            "max_value": maximum,
            "step": perturbation(minimum, maximum),
        }
        for name, default, minimum, maximum in parameters
    }
    decay = iterations**-GAMMA
    tune_lines = [
        "# Generated by tools/generate_spsa_surface.py from src/search_params.h.",
        f"# N = {iterations}; c_end = step * N ** -{GAMMA}.",
        "# Regenerate rather than edit; --check rejects drift.",
    ]
    for name, spec in surface.items():
        tune_lines.extend(
            [
                "",
                "[[parameters]]",
                f'name = "{name}"',
                f"initial = {spec['value']}",
                f"min = {spec['min_value']}",
                f"max = {spec['max_value']}",
                f"c_end = {spec['step'] * decay:.4f}",
            ]
        )
    run_text = """# Generated by tools/generate_spsa_surface.py.
# Supply the engine, horizon, seed and evidence directory through the wrapper.

extend = "../../colosseum/spsa-tune.toml"

[options]
tune = "search.tune.toml"
option = ["Hash=64", "Threads=1"]
"""
    return {
        CONFIG: json.dumps(surface, indent=4) + "\n",
        TUNE: "\n".join(tune_lines) + "\n",
        RUN: run_text,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--iterations", type=int, default=DEFAULT_ITERATIONS)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.iterations < 1:
        parser.error("--iterations must be positive")
    try:
        outputs = render(parse_parameters(HEADER.read_text(encoding="utf-8")), args.iterations)
    except ValueError as error:
        print(error, file=sys.stderr)
        return 2
    if args.check:
        stale = [
            path
            for path, wanted in outputs.items()
            if not path.is_file()
            or path.read_text(encoding="utf-8").replace("\r\n", "\n") != wanted
        ]
        for path in stale:
            print(f"stale or missing: {path}", file=sys.stderr)
        if stale:
            return 1
        print(f"{len(outputs)} generated files current ({len(parse_parameters(HEADER.read_text(encoding='utf-8')))} parameters)")
        return 0
    COLOSSEUM.mkdir(parents=True, exist_ok=True)
    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8", newline="")
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
